//! Advanced database operations including batch operations and transactions.
//!
//! Provides `BatchOperations` and `TransactionOperations` traits with safe,
//! parameterized query generation. Column names are validated against the
//! `Entity` schema to prevent SQL injection in dynamic queries.
//!
//! # Status
//!
//! This module defines the trait interfaces. Concrete implementations are
//! provided by the `impl_batch_operations!` and `impl_transaction_operations!`
//! macros in the repository module.
//!
//! # Safety
//!
//! All SQL queries generated by implementations use parameterized bindings
//! ($1, $2, …). Column names are validated against the Entity schema to
//! prevent injection attacks.

use async_trait::async_trait;
use sdkwork_database_sqlx::DatabasePool;

use crate::entity::Entity;
use crate::error::RepositoryError;

/// Batch operations for bulk database operations.
///
/// # Safety
///
/// All SQL queries generated by implementations use parameterized bindings
/// ($1, $2, …). Column names are validated against the Entity schema to
/// prevent injection attacks.
#[async_trait]
pub trait BatchOperations<E: Entity>: Send + Sync {
    /// Get the underlying database pool.
    fn pool(&self) -> &DatabasePool;

    /// Insert multiple entities in a single transaction.
    ///
    /// # Arguments
    ///
    /// - `entities`: Slice of entities to insert.
    ///
    /// # Returns
    ///
    /// - `Ok(())`: All entities inserted successfully.
    /// - `Err(RepositoryError::Database)`: Database error during insert.
    async fn insert_batch(&self, entities: &[E]) -> Result<(), RepositoryError>;

    /// Update multiple entities in a single transaction.
    ///
    /// # Arguments
    ///
    /// - `entities`: Slice of entities to update.
    ///
    /// # Returns
    ///
    /// - `Ok(())`: All entities updated successfully.
    /// - `Err(RepositoryError::Database)`: Database error during update.
    async fn update_batch(&self, entities: &[E]) -> Result<(), RepositoryError>;

    /// Delete multiple entities by their primary keys.
    ///
    /// # Arguments
    ///
    /// - `ids`: Slice of primary key values to delete.
    ///
    /// # Returns
    ///
    /// - `Ok(())`: All entities deleted successfully.
    /// - `Err(RepositoryError::NotFound)`: Entity not found.
    /// - `Err(RepositoryError::Database)`: Database error during delete.
    async fn delete_batch(&self, ids: &[i64]) -> Result<(), RepositoryError>;

    /// Upsert (insert or update) multiple entities.
    ///
    /// This operation checks if each entity exists by primary key, then
    /// either inserts or updates accordingly.
    ///
    /// # Arguments
    ///
    /// - `entities`: Slice of entities to upsert.
    ///
    /// # Returns
    ///
    /// - `Ok(())`: All entities upserted successfully.
    /// - `Err(RepositoryError::Database)`: Database error during upsert.
    async fn upsert_batch(&self, entities: &[E]) -> Result<(), RepositoryError>;
}

/// Transaction operations for safe multi-step database access.
///
/// Provides atomic execution of multiple database operations with automatic
/// rollback on failure.
#[async_trait]
pub trait TransactionOperations<E: Entity>: Send + Sync + Sized {
    /// Get the underlying database pool.
    fn pool(&self) -> &DatabasePool;

    /// Execute operations atomically within a transaction.
    ///
    /// The transaction is automatically committed if the operations return
    /// `Ok`, or rolled back if they return `Err`.
    ///
    /// # Arguments
    ///
    /// - `operations`: Closure that receives a transaction-scoped repository.
    ///
    /// # Returns
    ///
    /// - `Ok(R)`: Operations completed successfully, transaction committed.
    /// - `Err(RepositoryError)`: Operations failed, transaction rolled back.
    async fn execute_in_transaction<F, Fut, R>(&self, operations: F) -> Result<R, RepositoryError>
    where
        F: FnOnce(Self) -> Fut + Send,
        Fut: std::future::Future<Output = Result<R, RepositoryError>> + Send,
        R: Send;

    /// Execute operations with a savepoint for partial rollback.
    ///
    /// Savepoints allow nested transaction semantics where operations can
    /// be rolled back to a checkpoint without aborting the entire transaction.
    ///
    /// # Arguments
    ///
    /// - `operations`: Closure that receives a savepoint-scoped repository.
    ///
    /// # Returns
    ///
    /// - `Ok(R)`: Operations completed successfully.
    /// - `Err(RepositoryError)`: Operations failed, rolled back to savepoint.
    async fn execute_with_savepoint<F, Fut, R>(&self, operations: F) -> Result<R, RepositoryError>
    where
        F: FnOnce(Self) -> Fut + Send,
        Fut: std::future::Future<Output = Result<R, RepositoryError>> + Send,
        R: Send;
}

// ── Column Validation Helper ──────────────────────────────────────────────────

/// Validate that all column names in the input list are known to the entity schema.
///
/// # Security
///
/// This prevents SQL injection through column names in dynamic query generation.
/// Column names must match exactly the Entity::columns() definition.
///
/// # Arguments
///
/// - `columns`: Slice of column names to validate.
///
/// # Returns
///
/// - `Ok(())`: All column names are valid.
/// - `Err(RepositoryError::InvalidColumnName)`: Column not in entity schema.
///
/// # Security
///
/// This function validates column names against the entity schema to prevent
/// SQL injection through column name parameters.
#[allow(dead_code)]
fn validate_columns<E: Entity>(columns: &[&str]) -> Result<(), RepositoryError> {
    let allowed = E::columns();
    for col in columns {
        if !allowed.contains(col) {
            return Err(RepositoryError::InvalidColumnName(col.to_string()));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn validate_columns_accepts_known_columns() {
        // Test would need a concrete Entity implementation
        // This is a compile-time validation test
    }
}
